#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyDaiLy")]
	public partial class QLDLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBAOCAOCONGNO(BAOCAOCONGNO instance);
    partial void UpdateBAOCAOCONGNO(BAOCAOCONGNO instance);
    partial void DeleteBAOCAOCONGNO(BAOCAOCONGNO instance);
    partial void InsertTHAMSO(THAMSO instance);
    partial void UpdateTHAMSO(THAMSO instance);
    partial void DeleteTHAMSO(THAMSO instance);
    partial void InsertBAOCAODOANHSO(BAOCAODOANHSO instance);
    partial void UpdateBAOCAODOANHSO(BAOCAODOANHSO instance);
    partial void DeleteBAOCAODOANHSO(BAOCAODOANHSO instance);
    partial void InsertCONGNO_DAILY(CONGNO_DAILY instance);
    partial void UpdateCONGNO_DAILY(CONGNO_DAILY instance);
    partial void DeleteCONGNO_DAILY(CONGNO_DAILY instance);
    partial void InsertDAILY(DAILY instance);
    partial void UpdateDAILY(DAILY instance);
    partial void DeleteDAILY(DAILY instance);
    partial void InsertDOANHSO_DAILY(DOANHSO_DAILY instance);
    partial void UpdateDOANHSO_DAILY(DOANHSO_DAILY instance);
    partial void DeleteDOANHSO_DAILY(DOANHSO_DAILY instance);
    partial void InsertDONVITINH(DONVITINH instance);
    partial void UpdateDONVITINH(DONVITINH instance);
    partial void DeleteDONVITINH(DONVITINH instance);
    partial void InsertLOAIDAILY(LOAIDAILY instance);
    partial void UpdateLOAIDAILY(LOAIDAILY instance);
    partial void DeleteLOAIDAILY(LOAIDAILY instance);
    partial void InsertMATHANG(MATHANG instance);
    partial void UpdateMATHANG(MATHANG instance);
    partial void DeleteMATHANG(MATHANG instance);
    partial void InsertPHIEUTHUTIEN(PHIEUTHUTIEN instance);
    partial void UpdatePHIEUTHUTIEN(PHIEUTHUTIEN instance);
    partial void DeletePHIEUTHUTIEN(PHIEUTHUTIEN instance);
    partial void InsertPHIEUXUAT_MATHANG(PHIEUXUAT_MATHANG instance);
    partial void UpdatePHIEUXUAT_MATHANG(PHIEUXUAT_MATHANG instance);
    partial void DeletePHIEUXUAT_MATHANG(PHIEUXUAT_MATHANG instance);
    partial void InsertPHIEUXUATHANG(PHIEUXUATHANG instance);
    partial void UpdatePHIEUXUATHANG(PHIEUXUATHANG instance);
    partial void DeletePHIEUXUATHANG(PHIEUXUATHANG instance);
    partial void InsertQUAN(QUAN instance);
    partial void UpdateQUAN(QUAN instance);
    partial void DeleteQUAN(QUAN instance);
    #endregion
		
		public QLDLDataContext() : 
				base(global::Project.Properties.Settings.Default.QuanLyDaiLyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BAOCAOCONGNO> BAOCAOCONGNOs
		{
			get
			{
				return this.GetTable<BAOCAOCONGNO>();
			}
		}
		
		public System.Data.Linq.Table<THAMSO> THAMSOs
		{
			get
			{
				return this.GetTable<THAMSO>();
			}
		}
		
		public System.Data.Linq.Table<BAOCAODOANHSO> BAOCAODOANHSOs
		{
			get
			{
				return this.GetTable<BAOCAODOANHSO>();
			}
		}
		
		public System.Data.Linq.Table<CONGNO_DAILY> CONGNO_DAILies
		{
			get
			{
				return this.GetTable<CONGNO_DAILY>();
			}
		}
		
		public System.Data.Linq.Table<DAILY> DAILies
		{
			get
			{
				return this.GetTable<DAILY>();
			}
		}
		
		public System.Data.Linq.Table<DOANHSO_DAILY> DOANHSO_DAILies
		{
			get
			{
				return this.GetTable<DOANHSO_DAILY>();
			}
		}
		
		public System.Data.Linq.Table<DONVITINH> DONVITINHs
		{
			get
			{
				return this.GetTable<DONVITINH>();
			}
		}
		
		public System.Data.Linq.Table<LOAIDAILY> LOAIDAILies
		{
			get
			{
				return this.GetTable<LOAIDAILY>();
			}
		}
		
		public System.Data.Linq.Table<MATHANG> MATHANGs
		{
			get
			{
				return this.GetTable<MATHANG>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTHUTIEN> PHIEUTHUTIENs
		{
			get
			{
				return this.GetTable<PHIEUTHUTIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUXUAT_MATHANG> PHIEUXUAT_MATHANGs
		{
			get
			{
				return this.GetTable<PHIEUXUAT_MATHANG>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUXUATHANG> PHIEUXUATHANGs
		{
			get
			{
				return this.GetTable<PHIEUXUATHANG>();
			}
		}
		
		public System.Data.Linq.Table<QUAN> QUANs
		{
			get
			{
				return this.GetTable<QUAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAOCAOCONGNO")]
	public partial class BAOCAOCONGNO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBaoCaoCongNo;
		
		private System.Nullable<int> _Thang;
		
		private EntitySet<CONGNO_DAILY> _CONGNO_DAILies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaoCaoCongNoChanging(string value);
    partial void OnMaBaoCaoCongNoChanged();
    partial void OnThangChanging(System.Nullable<int> value);
    partial void OnThangChanged();
    #endregion
		
		public BAOCAOCONGNO()
		{
			this._CONGNO_DAILies = new EntitySet<CONGNO_DAILY>(new Action<CONGNO_DAILY>(this.attach_CONGNO_DAILies), new Action<CONGNO_DAILY>(this.detach_CONGNO_DAILies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaoCaoCongNo", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBaoCaoCongNo
		{
			get
			{
				return this._MaBaoCaoCongNo;
			}
			set
			{
				if ((this._MaBaoCaoCongNo != value))
				{
					this.OnMaBaoCaoCongNoChanging(value);
					this.SendPropertyChanging();
					this._MaBaoCaoCongNo = value;
					this.SendPropertyChanged("MaBaoCaoCongNo");
					this.OnMaBaoCaoCongNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int")]
		public System.Nullable<int> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this.OnThangChanging(value);
					this.SendPropertyChanging();
					this._Thang = value;
					this.SendPropertyChanged("Thang");
					this.OnThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAOCAOCONGNO_CONGNO_DAILY", Storage="_CONGNO_DAILies", ThisKey="MaBaoCaoCongNo", OtherKey="MaBaoCaoCongNo")]
		public EntitySet<CONGNO_DAILY> CONGNO_DAILies
		{
			get
			{
				return this._CONGNO_DAILies;
			}
			set
			{
				this._CONGNO_DAILies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONGNO_DAILies(CONGNO_DAILY entity)
		{
			this.SendPropertyChanging();
			entity.BAOCAOCONGNO = this;
		}
		
		private void detach_CONGNO_DAILies(CONGNO_DAILY entity)
		{
			this.SendPropertyChanging();
			entity.BAOCAOCONGNO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THAMSO")]
	public partial class THAMSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _SoDaiLyToiDaQuan;
		
		private System.Nullable<int> _SoMatHang;
		
		private System.Nullable<int> _SoDonViTinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSoDaiLyToiDaQuanChanging(System.Nullable<int> value);
    partial void OnSoDaiLyToiDaQuanChanged();
    partial void OnSoMatHangChanging(System.Nullable<int> value);
    partial void OnSoMatHangChanged();
    partial void OnSoDonViTinhChanging(System.Nullable<int> value);
    partial void OnSoDonViTinhChanged();
    #endregion
		
		public THAMSO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDaiLyToiDaQuan", DbType="Int")]
		public System.Nullable<int> SoDaiLyToiDaQuan
		{
			get
			{
				return this._SoDaiLyToiDaQuan;
			}
			set
			{
				if ((this._SoDaiLyToiDaQuan != value))
				{
					this.OnSoDaiLyToiDaQuanChanging(value);
					this.SendPropertyChanging();
					this._SoDaiLyToiDaQuan = value;
					this.SendPropertyChanged("SoDaiLyToiDaQuan");
					this.OnSoDaiLyToiDaQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoMatHang", DbType="Int")]
		public System.Nullable<int> SoMatHang
		{
			get
			{
				return this._SoMatHang;
			}
			set
			{
				if ((this._SoMatHang != value))
				{
					this.OnSoMatHangChanging(value);
					this.SendPropertyChanging();
					this._SoMatHang = value;
					this.SendPropertyChanged("SoMatHang");
					this.OnSoMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDonViTinh", DbType="Int")]
		public System.Nullable<int> SoDonViTinh
		{
			get
			{
				return this._SoDonViTinh;
			}
			set
			{
				if ((this._SoDonViTinh != value))
				{
					this.OnSoDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._SoDonViTinh = value;
					this.SendPropertyChanged("SoDonViTinh");
					this.OnSoDonViTinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAOCAODOANHSO")]
	public partial class BAOCAODOANHSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBaoCaoDoanhSo;
		
		private System.Nullable<int> _Thang;
		
		private EntitySet<DOANHSO_DAILY> _DOANHSO_DAILies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaoCaoDoanhSoChanging(string value);
    partial void OnMaBaoCaoDoanhSoChanged();
    partial void OnThangChanging(System.Nullable<int> value);
    partial void OnThangChanged();
    #endregion
		
		public BAOCAODOANHSO()
		{
			this._DOANHSO_DAILies = new EntitySet<DOANHSO_DAILY>(new Action<DOANHSO_DAILY>(this.attach_DOANHSO_DAILies), new Action<DOANHSO_DAILY>(this.detach_DOANHSO_DAILies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaoCaoDoanhSo", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBaoCaoDoanhSo
		{
			get
			{
				return this._MaBaoCaoDoanhSo;
			}
			set
			{
				if ((this._MaBaoCaoDoanhSo != value))
				{
					this.OnMaBaoCaoDoanhSoChanging(value);
					this.SendPropertyChanging();
					this._MaBaoCaoDoanhSo = value;
					this.SendPropertyChanged("MaBaoCaoDoanhSo");
					this.OnMaBaoCaoDoanhSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int")]
		public System.Nullable<int> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this.OnThangChanging(value);
					this.SendPropertyChanging();
					this._Thang = value;
					this.SendPropertyChanged("Thang");
					this.OnThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAOCAODOANHSO_DOANHSO_DAILY", Storage="_DOANHSO_DAILies", ThisKey="MaBaoCaoDoanhSo", OtherKey="MaBaoCaoDoanhSo")]
		public EntitySet<DOANHSO_DAILY> DOANHSO_DAILies
		{
			get
			{
				return this._DOANHSO_DAILies;
			}
			set
			{
				this._DOANHSO_DAILies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DOANHSO_DAILies(DOANHSO_DAILY entity)
		{
			this.SendPropertyChanging();
			entity.BAOCAODOANHSO = this;
		}
		
		private void detach_DOANHSO_DAILies(DOANHSO_DAILY entity)
		{
			this.SendPropertyChanging();
			entity.BAOCAODOANHSO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONGNO_DAILY")]
	public partial class CONGNO_DAILY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBaoCaoCongNo;
		
		private string _MaDaiLy;
		
		private System.Nullable<int> _NoDau;
		
		private System.Nullable<int> _PhatSinh;
		
		private System.Nullable<int> _NoCuoi;
		
		private EntityRef<BAOCAOCONGNO> _BAOCAOCONGNO;
		
		private EntityRef<DAILY> _DAILY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaoCaoCongNoChanging(string value);
    partial void OnMaBaoCaoCongNoChanged();
    partial void OnMaDaiLyChanging(string value);
    partial void OnMaDaiLyChanged();
    partial void OnNoDauChanging(System.Nullable<int> value);
    partial void OnNoDauChanged();
    partial void OnPhatSinhChanging(System.Nullable<int> value);
    partial void OnPhatSinhChanged();
    partial void OnNoCuoiChanging(System.Nullable<int> value);
    partial void OnNoCuoiChanged();
    #endregion
		
		public CONGNO_DAILY()
		{
			this._BAOCAOCONGNO = default(EntityRef<BAOCAOCONGNO>);
			this._DAILY = default(EntityRef<DAILY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaoCaoCongNo", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBaoCaoCongNo
		{
			get
			{
				return this._MaBaoCaoCongNo;
			}
			set
			{
				if ((this._MaBaoCaoCongNo != value))
				{
					if (this._BAOCAOCONGNO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBaoCaoCongNoChanging(value);
					this.SendPropertyChanging();
					this._MaBaoCaoCongNo = value;
					this.SendPropertyChanged("MaBaoCaoCongNo");
					this.OnMaBaoCaoCongNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					if (this._DAILY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaDaiLy = value;
					this.SendPropertyChanged("MaDaiLy");
					this.OnMaDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDau", DbType="Int")]
		public System.Nullable<int> NoDau
		{
			get
			{
				return this._NoDau;
			}
			set
			{
				if ((this._NoDau != value))
				{
					this.OnNoDauChanging(value);
					this.SendPropertyChanging();
					this._NoDau = value;
					this.SendPropertyChanged("NoDau");
					this.OnNoDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhatSinh", DbType="Int")]
		public System.Nullable<int> PhatSinh
		{
			get
			{
				return this._PhatSinh;
			}
			set
			{
				if ((this._PhatSinh != value))
				{
					this.OnPhatSinhChanging(value);
					this.SendPropertyChanging();
					this._PhatSinh = value;
					this.SendPropertyChanged("PhatSinh");
					this.OnPhatSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoCuoi", DbType="Int")]
		public System.Nullable<int> NoCuoi
		{
			get
			{
				return this._NoCuoi;
			}
			set
			{
				if ((this._NoCuoi != value))
				{
					this.OnNoCuoiChanging(value);
					this.SendPropertyChanging();
					this._NoCuoi = value;
					this.SendPropertyChanged("NoCuoi");
					this.OnNoCuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAOCAOCONGNO_CONGNO_DAILY", Storage="_BAOCAOCONGNO", ThisKey="MaBaoCaoCongNo", OtherKey="MaBaoCaoCongNo", IsForeignKey=true)]
		public BAOCAOCONGNO BAOCAOCONGNO
		{
			get
			{
				return this._BAOCAOCONGNO.Entity;
			}
			set
			{
				BAOCAOCONGNO previousValue = this._BAOCAOCONGNO.Entity;
				if (((previousValue != value) 
							|| (this._BAOCAOCONGNO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BAOCAOCONGNO.Entity = null;
						previousValue.CONGNO_DAILies.Remove(this);
					}
					this._BAOCAOCONGNO.Entity = value;
					if ((value != null))
					{
						value.CONGNO_DAILies.Add(this);
						this._MaBaoCaoCongNo = value.MaBaoCaoCongNo;
					}
					else
					{
						this._MaBaoCaoCongNo = default(string);
					}
					this.SendPropertyChanged("BAOCAOCONGNO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_CONGNO_DAILY", Storage="_DAILY", ThisKey="MaDaiLy", OtherKey="MaDaiLy", IsForeignKey=true)]
		public DAILY DAILY
		{
			get
			{
				return this._DAILY.Entity;
			}
			set
			{
				DAILY previousValue = this._DAILY.Entity;
				if (((previousValue != value) 
							|| (this._DAILY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DAILY.Entity = null;
						previousValue.CONGNO_DAILies.Remove(this);
					}
					this._DAILY.Entity = value;
					if ((value != null))
					{
						value.CONGNO_DAILies.Add(this);
						this._MaDaiLy = value.MaDaiLy;
					}
					else
					{
						this._MaDaiLy = default(string);
					}
					this.SendPropertyChanged("DAILY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DAILY")]
	public partial class DAILY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDaiLy;
		
		private string _TenDaiLy;
		
		private string _DienThoai;
		
		private string _DiaChi;
		
		private System.Nullable<System.DateTime> _NgayTiepNhan;
		
		private string _Email;
		
		private System.Nullable<int> _TienNo;
		
		private System.Nullable<int> _MaLoaiDaiLy;
		
		private string _MaQuan;
		
		private EntitySet<CONGNO_DAILY> _CONGNO_DAILies;
		
		private EntitySet<DOANHSO_DAILY> _DOANHSO_DAILies;
		
		private EntitySet<PHIEUTHUTIEN> _PHIEUTHUTIENs;
		
		private EntitySet<PHIEUXUATHANG> _PHIEUXUATHANGs;
		
		private EntityRef<LOAIDAILY> _LOAIDAILY;
		
		private EntityRef<QUAN> _QUAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDaiLyChanging(string value);
    partial void OnMaDaiLyChanged();
    partial void OnTenDaiLyChanging(string value);
    partial void OnTenDaiLyChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnNgayTiepNhanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTiepNhanChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTienNoChanging(System.Nullable<int> value);
    partial void OnTienNoChanged();
    partial void OnMaLoaiDaiLyChanging(System.Nullable<int> value);
    partial void OnMaLoaiDaiLyChanged();
    partial void OnMaQuanChanging(string value);
    partial void OnMaQuanChanged();
    #endregion
		
		public DAILY()
		{
			this._CONGNO_DAILies = new EntitySet<CONGNO_DAILY>(new Action<CONGNO_DAILY>(this.attach_CONGNO_DAILies), new Action<CONGNO_DAILY>(this.detach_CONGNO_DAILies));
			this._DOANHSO_DAILies = new EntitySet<DOANHSO_DAILY>(new Action<DOANHSO_DAILY>(this.attach_DOANHSO_DAILies), new Action<DOANHSO_DAILY>(this.detach_DOANHSO_DAILies));
			this._PHIEUTHUTIENs = new EntitySet<PHIEUTHUTIEN>(new Action<PHIEUTHUTIEN>(this.attach_PHIEUTHUTIENs), new Action<PHIEUTHUTIEN>(this.detach_PHIEUTHUTIENs));
			this._PHIEUXUATHANGs = new EntitySet<PHIEUXUATHANG>(new Action<PHIEUXUATHANG>(this.attach_PHIEUXUATHANGs), new Action<PHIEUXUATHANG>(this.detach_PHIEUXUATHANGs));
			this._LOAIDAILY = default(EntityRef<LOAIDAILY>);
			this._QUAN = default(EntityRef<QUAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					this.OnMaDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaDaiLy = value;
					this.SendPropertyChanged("MaDaiLy");
					this.OnMaDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDaiLy", DbType="NVarChar(50)")]
		public string TenDaiLy
		{
			get
			{
				return this._TenDaiLy;
			}
			set
			{
				if ((this._TenDaiLy != value))
				{
					this.OnTenDaiLyChanging(value);
					this.SendPropertyChanging();
					this._TenDaiLy = value;
					this.SendPropertyChanged("TenDaiLy");
					this.OnTenDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="Char(15)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(231)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTiepNhan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTiepNhan
		{
			get
			{
				return this._NgayTiepNhan;
			}
			set
			{
				if ((this._NgayTiepNhan != value))
				{
					this.OnNgayTiepNhanChanging(value);
					this.SendPropertyChanging();
					this._NgayTiepNhan = value;
					this.SendPropertyChanged("NgayTiepNhan");
					this.OnNgayTiepNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Char(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienNo", DbType="Int")]
		public System.Nullable<int> TienNo
		{
			get
			{
				return this._TienNo;
			}
			set
			{
				if ((this._TienNo != value))
				{
					this.OnTienNoChanging(value);
					this.SendPropertyChanging();
					this._TienNo = value;
					this.SendPropertyChanged("TienNo");
					this.OnTienNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiDaiLy", DbType="Int")]
		public System.Nullable<int> MaLoaiDaiLy
		{
			get
			{
				return this._MaLoaiDaiLy;
			}
			set
			{
				if ((this._MaLoaiDaiLy != value))
				{
					if (this._LOAIDAILY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiDaiLy = value;
					this.SendPropertyChanged("MaLoaiDaiLy");
					this.OnMaLoaiDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuan", DbType="Char(10)")]
		public string MaQuan
		{
			get
			{
				return this._MaQuan;
			}
			set
			{
				if ((this._MaQuan != value))
				{
					if (this._QUAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuanChanging(value);
					this.SendPropertyChanging();
					this._MaQuan = value;
					this.SendPropertyChanged("MaQuan");
					this.OnMaQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_CONGNO_DAILY", Storage="_CONGNO_DAILies", ThisKey="MaDaiLy", OtherKey="MaDaiLy")]
		public EntitySet<CONGNO_DAILY> CONGNO_DAILies
		{
			get
			{
				return this._CONGNO_DAILies;
			}
			set
			{
				this._CONGNO_DAILies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_DOANHSO_DAILY", Storage="_DOANHSO_DAILies", ThisKey="MaDaiLy", OtherKey="MaDaiLy")]
		public EntitySet<DOANHSO_DAILY> DOANHSO_DAILies
		{
			get
			{
				return this._DOANHSO_DAILies;
			}
			set
			{
				this._DOANHSO_DAILies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_PHIEUTHUTIEN", Storage="_PHIEUTHUTIENs", ThisKey="MaDaiLy", OtherKey="MaDaiLy")]
		public EntitySet<PHIEUTHUTIEN> PHIEUTHUTIENs
		{
			get
			{
				return this._PHIEUTHUTIENs;
			}
			set
			{
				this._PHIEUTHUTIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_PHIEUXUATHANG", Storage="_PHIEUXUATHANGs", ThisKey="MaDaiLy", OtherKey="MaDaiLy")]
		public EntitySet<PHIEUXUATHANG> PHIEUXUATHANGs
		{
			get
			{
				return this._PHIEUXUATHANGs;
			}
			set
			{
				this._PHIEUXUATHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIDAILY_DAILY", Storage="_LOAIDAILY", ThisKey="MaLoaiDaiLy", OtherKey="MaLoaiDaiLy", IsForeignKey=true)]
		public LOAIDAILY LOAIDAILY
		{
			get
			{
				return this._LOAIDAILY.Entity;
			}
			set
			{
				LOAIDAILY previousValue = this._LOAIDAILY.Entity;
				if (((previousValue != value) 
							|| (this._LOAIDAILY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIDAILY.Entity = null;
						previousValue.DAILies.Remove(this);
					}
					this._LOAIDAILY.Entity = value;
					if ((value != null))
					{
						value.DAILies.Add(this);
						this._MaLoaiDaiLy = value.MaLoaiDaiLy;
					}
					else
					{
						this._MaLoaiDaiLy = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAIDAILY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUAN_DAILY", Storage="_QUAN", ThisKey="MaQuan", OtherKey="MaQuan", IsForeignKey=true)]
		public QUAN QUAN
		{
			get
			{
				return this._QUAN.Entity;
			}
			set
			{
				QUAN previousValue = this._QUAN.Entity;
				if (((previousValue != value) 
							|| (this._QUAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QUAN.Entity = null;
						previousValue.DAILies.Remove(this);
					}
					this._QUAN.Entity = value;
					if ((value != null))
					{
						value.DAILies.Add(this);
						this._MaQuan = value.MaQuan;
					}
					else
					{
						this._MaQuan = default(string);
					}
					this.SendPropertyChanged("QUAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONGNO_DAILies(CONGNO_DAILY entity)
		{
			this.SendPropertyChanging();
			entity.DAILY = this;
		}
		
		private void detach_CONGNO_DAILies(CONGNO_DAILY entity)
		{
			this.SendPropertyChanging();
			entity.DAILY = null;
		}
		
		private void attach_DOANHSO_DAILies(DOANHSO_DAILY entity)
		{
			this.SendPropertyChanging();
			entity.DAILY = this;
		}
		
		private void detach_DOANHSO_DAILies(DOANHSO_DAILY entity)
		{
			this.SendPropertyChanging();
			entity.DAILY = null;
		}
		
		private void attach_PHIEUTHUTIENs(PHIEUTHUTIEN entity)
		{
			this.SendPropertyChanging();
			entity.DAILY = this;
		}
		
		private void detach_PHIEUTHUTIENs(PHIEUTHUTIEN entity)
		{
			this.SendPropertyChanging();
			entity.DAILY = null;
		}
		
		private void attach_PHIEUXUATHANGs(PHIEUXUATHANG entity)
		{
			this.SendPropertyChanging();
			entity.DAILY = this;
		}
		
		private void detach_PHIEUXUATHANGs(PHIEUXUATHANG entity)
		{
			this.SendPropertyChanging();
			entity.DAILY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOANHSO_DAILY")]
	public partial class DOANHSO_DAILY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBaoCaoDoanhSo;
		
		private string _MaDaiLy;
		
		private System.Nullable<int> _SoPhieuXuat;
		
		private System.Nullable<int> _TongTriGia;
		
		private System.Nullable<int> _TyLe;
		
		private EntityRef<DAILY> _DAILY;
		
		private EntityRef<BAOCAODOANHSO> _BAOCAODOANHSO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaoCaoDoanhSoChanging(string value);
    partial void OnMaBaoCaoDoanhSoChanged();
    partial void OnMaDaiLyChanging(string value);
    partial void OnMaDaiLyChanged();
    partial void OnSoPhieuXuatChanging(System.Nullable<int> value);
    partial void OnSoPhieuXuatChanged();
    partial void OnTongTriGiaChanging(System.Nullable<int> value);
    partial void OnTongTriGiaChanged();
    partial void OnTyLeChanging(System.Nullable<int> value);
    partial void OnTyLeChanged();
    #endregion
		
		public DOANHSO_DAILY()
		{
			this._DAILY = default(EntityRef<DAILY>);
			this._BAOCAODOANHSO = default(EntityRef<BAOCAODOANHSO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaoCaoDoanhSo", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBaoCaoDoanhSo
		{
			get
			{
				return this._MaBaoCaoDoanhSo;
			}
			set
			{
				if ((this._MaBaoCaoDoanhSo != value))
				{
					if (this._BAOCAODOANHSO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBaoCaoDoanhSoChanging(value);
					this.SendPropertyChanging();
					this._MaBaoCaoDoanhSo = value;
					this.SendPropertyChanged("MaBaoCaoDoanhSo");
					this.OnMaBaoCaoDoanhSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					if (this._DAILY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaDaiLy = value;
					this.SendPropertyChanged("MaDaiLy");
					this.OnMaDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieuXuat", DbType="Int")]
		public System.Nullable<int> SoPhieuXuat
		{
			get
			{
				return this._SoPhieuXuat;
			}
			set
			{
				if ((this._SoPhieuXuat != value))
				{
					this.OnSoPhieuXuatChanging(value);
					this.SendPropertyChanging();
					this._SoPhieuXuat = value;
					this.SendPropertyChanged("SoPhieuXuat");
					this.OnSoPhieuXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTriGia", DbType="Int")]
		public System.Nullable<int> TongTriGia
		{
			get
			{
				return this._TongTriGia;
			}
			set
			{
				if ((this._TongTriGia != value))
				{
					this.OnTongTriGiaChanging(value);
					this.SendPropertyChanging();
					this._TongTriGia = value;
					this.SendPropertyChanged("TongTriGia");
					this.OnTongTriGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TyLe", DbType="Int")]
		public System.Nullable<int> TyLe
		{
			get
			{
				return this._TyLe;
			}
			set
			{
				if ((this._TyLe != value))
				{
					this.OnTyLeChanging(value);
					this.SendPropertyChanging();
					this._TyLe = value;
					this.SendPropertyChanged("TyLe");
					this.OnTyLeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_DOANHSO_DAILY", Storage="_DAILY", ThisKey="MaDaiLy", OtherKey="MaDaiLy", IsForeignKey=true)]
		public DAILY DAILY
		{
			get
			{
				return this._DAILY.Entity;
			}
			set
			{
				DAILY previousValue = this._DAILY.Entity;
				if (((previousValue != value) 
							|| (this._DAILY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DAILY.Entity = null;
						previousValue.DOANHSO_DAILies.Remove(this);
					}
					this._DAILY.Entity = value;
					if ((value != null))
					{
						value.DOANHSO_DAILies.Add(this);
						this._MaDaiLy = value.MaDaiLy;
					}
					else
					{
						this._MaDaiLy = default(string);
					}
					this.SendPropertyChanged("DAILY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAOCAODOANHSO_DOANHSO_DAILY", Storage="_BAOCAODOANHSO", ThisKey="MaBaoCaoDoanhSo", OtherKey="MaBaoCaoDoanhSo", IsForeignKey=true)]
		public BAOCAODOANHSO BAOCAODOANHSO
		{
			get
			{
				return this._BAOCAODOANHSO.Entity;
			}
			set
			{
				BAOCAODOANHSO previousValue = this._BAOCAODOANHSO.Entity;
				if (((previousValue != value) 
							|| (this._BAOCAODOANHSO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BAOCAODOANHSO.Entity = null;
						previousValue.DOANHSO_DAILies.Remove(this);
					}
					this._BAOCAODOANHSO.Entity = value;
					if ((value != null))
					{
						value.DOANHSO_DAILies.Add(this);
						this._MaBaoCaoDoanhSo = value.MaBaoCaoDoanhSo;
					}
					else
					{
						this._MaBaoCaoDoanhSo = default(string);
					}
					this.SendPropertyChanged("BAOCAODOANHSO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONVITINH")]
	public partial class DONVITINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonViTinh;
		
		private string _TenDonViTinh;
		
		private EntitySet<PHIEUXUAT_MATHANG> _PHIEUXUAT_MATHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonViTinhChanging(int value);
    partial void OnMaDonViTinhChanged();
    partial void OnTenDonViTinhChanging(string value);
    partial void OnTenDonViTinhChanged();
    #endregion
		
		public DONVITINH()
		{
			this._PHIEUXUAT_MATHANGs = new EntitySet<PHIEUXUAT_MATHANG>(new Action<PHIEUXUAT_MATHANG>(this.attach_PHIEUXUAT_MATHANGs), new Action<PHIEUXUAT_MATHANG>(this.detach_PHIEUXUAT_MATHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonViTinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDonViTinh
		{
			get
			{
				return this._MaDonViTinh;
			}
			set
			{
				if ((this._MaDonViTinh != value))
				{
					this.OnMaDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._MaDonViTinh = value;
					this.SendPropertyChanged("MaDonViTinh");
					this.OnMaDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonViTinh", DbType="NVarChar(50)")]
		public string TenDonViTinh
		{
			get
			{
				return this._TenDonViTinh;
			}
			set
			{
				if ((this._TenDonViTinh != value))
				{
					this.OnTenDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._TenDonViTinh = value;
					this.SendPropertyChanged("TenDonViTinh");
					this.OnTenDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONVITINH_PHIEUXUAT_MATHANG", Storage="_PHIEUXUAT_MATHANGs", ThisKey="MaDonViTinh", OtherKey="MaDonViTinh")]
		public EntitySet<PHIEUXUAT_MATHANG> PHIEUXUAT_MATHANGs
		{
			get
			{
				return this._PHIEUXUAT_MATHANGs;
			}
			set
			{
				this._PHIEUXUAT_MATHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUXUAT_MATHANGs(PHIEUXUAT_MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONVITINH = this;
		}
		
		private void detach_PHIEUXUAT_MATHANGs(PHIEUXUAT_MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONVITINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIDAILY")]
	public partial class LOAIDAILY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiDaiLy;
		
		private string _TenLoaiDaiLy;
		
		private System.Nullable<int> _TienNoToiDa;
		
		private EntitySet<DAILY> _DAILies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiDaiLyChanging(int value);
    partial void OnMaLoaiDaiLyChanged();
    partial void OnTenLoaiDaiLyChanging(string value);
    partial void OnTenLoaiDaiLyChanged();
    partial void OnTienNoToiDaChanging(System.Nullable<int> value);
    partial void OnTienNoToiDaChanged();
    #endregion
		
		public LOAIDAILY()
		{
			this._DAILies = new EntitySet<DAILY>(new Action<DAILY>(this.attach_DAILies), new Action<DAILY>(this.detach_DAILies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiDaiLy", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiDaiLy
		{
			get
			{
				return this._MaLoaiDaiLy;
			}
			set
			{
				if ((this._MaLoaiDaiLy != value))
				{
					this.OnMaLoaiDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiDaiLy = value;
					this.SendPropertyChanged("MaLoaiDaiLy");
					this.OnMaLoaiDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiDaiLy", DbType="NVarChar(100)")]
		public string TenLoaiDaiLy
		{
			get
			{
				return this._TenLoaiDaiLy;
			}
			set
			{
				if ((this._TenLoaiDaiLy != value))
				{
					this.OnTenLoaiDaiLyChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiDaiLy = value;
					this.SendPropertyChanged("TenLoaiDaiLy");
					this.OnTenLoaiDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienNoToiDa", DbType="Int")]
		public System.Nullable<int> TienNoToiDa
		{
			get
			{
				return this._TienNoToiDa;
			}
			set
			{
				if ((this._TienNoToiDa != value))
				{
					this.OnTienNoToiDaChanging(value);
					this.SendPropertyChanging();
					this._TienNoToiDa = value;
					this.SendPropertyChanged("TienNoToiDa");
					this.OnTienNoToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIDAILY_DAILY", Storage="_DAILies", ThisKey="MaLoaiDaiLy", OtherKey="MaLoaiDaiLy")]
		public EntitySet<DAILY> DAILies
		{
			get
			{
				return this._DAILies;
			}
			set
			{
				this._DAILies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DAILies(DAILY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIDAILY = this;
		}
		
		private void detach_DAILies(DAILY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIDAILY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MATHANG")]
	public partial class MATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMatHang;
		
		private string _TenMatHang;
		
		private System.Nullable<int> _DonGia;
		
		private System.Nullable<int> _SoLuongTon;
		
		private EntitySet<PHIEUXUAT_MATHANG> _PHIEUXUAT_MATHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMatHangChanging(string value);
    partial void OnMaMatHangChanged();
    partial void OnTenMatHangChanging(string value);
    partial void OnTenMatHangChanged();
    partial void OnDonGiaChanging(System.Nullable<int> value);
    partial void OnDonGiaChanged();
    partial void OnSoLuongTonChanging(System.Nullable<int> value);
    partial void OnSoLuongTonChanged();
    #endregion
		
		public MATHANG()
		{
			this._PHIEUXUAT_MATHANGs = new EntitySet<PHIEUXUAT_MATHANG>(new Action<PHIEUXUAT_MATHANG>(this.attach_PHIEUXUAT_MATHANGs), new Action<PHIEUXUAT_MATHANG>(this.detach_PHIEUXUAT_MATHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMatHang", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMatHang
		{
			get
			{
				return this._MaMatHang;
			}
			set
			{
				if ((this._MaMatHang != value))
				{
					this.OnMaMatHangChanging(value);
					this.SendPropertyChanging();
					this._MaMatHang = value;
					this.SendPropertyChanged("MaMatHang");
					this.OnMaMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMatHang", DbType="NVarChar(100)")]
		public string TenMatHang
		{
			get
			{
				return this._TenMatHang;
			}
			set
			{
				if ((this._TenMatHang != value))
				{
					this.OnTenMatHangChanging(value);
					this.SendPropertyChanging();
					this._TenMatHang = value;
					this.SendPropertyChanged("TenMatHang");
					this.OnTenMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int")]
		public System.Nullable<int> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTon", DbType="Int")]
		public System.Nullable<int> SoLuongTon
		{
			get
			{
				return this._SoLuongTon;
			}
			set
			{
				if ((this._SoLuongTon != value))
				{
					this.OnSoLuongTonChanging(value);
					this.SendPropertyChanging();
					this._SoLuongTon = value;
					this.SendPropertyChanged("SoLuongTon");
					this.OnSoLuongTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATHANG_PHIEUXUAT_MATHANG", Storage="_PHIEUXUAT_MATHANGs", ThisKey="MaMatHang", OtherKey="MaMatHang")]
		public EntitySet<PHIEUXUAT_MATHANG> PHIEUXUAT_MATHANGs
		{
			get
			{
				return this._PHIEUXUAT_MATHANGs;
			}
			set
			{
				this._PHIEUXUAT_MATHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUXUAT_MATHANGs(PHIEUXUAT_MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.MATHANG = this;
		}
		
		private void detach_PHIEUXUAT_MATHANGs(PHIEUXUAT_MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.MATHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTHUTIEN")]
	public partial class PHIEUTHUTIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuThu;
		
		private System.Nullable<System.DateTime> _NgayThuTien;
		
		private System.Nullable<int> _SoTienThu;
		
		private string _MaDaiLy;
		
		private EntityRef<DAILY> _DAILY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuThuChanging(string value);
    partial void OnMaPhieuThuChanged();
    partial void OnNgayThuTienChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThuTienChanged();
    partial void OnSoTienThuChanging(System.Nullable<int> value);
    partial void OnSoTienThuChanged();
    partial void OnMaDaiLyChanging(string value);
    partial void OnMaDaiLyChanged();
    #endregion
		
		public PHIEUTHUTIEN()
		{
			this._DAILY = default(EntityRef<DAILY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuThu", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuThu
		{
			get
			{
				return this._MaPhieuThu;
			}
			set
			{
				if ((this._MaPhieuThu != value))
				{
					this.OnMaPhieuThuChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuThu = value;
					this.SendPropertyChanged("MaPhieuThu");
					this.OnMaPhieuThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThuTien", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayThuTien
		{
			get
			{
				return this._NgayThuTien;
			}
			set
			{
				if ((this._NgayThuTien != value))
				{
					this.OnNgayThuTienChanging(value);
					this.SendPropertyChanging();
					this._NgayThuTien = value;
					this.SendPropertyChanged("NgayThuTien");
					this.OnNgayThuTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienThu", DbType="Int")]
		public System.Nullable<int> SoTienThu
		{
			get
			{
				return this._SoTienThu;
			}
			set
			{
				if ((this._SoTienThu != value))
				{
					this.OnSoTienThuChanging(value);
					this.SendPropertyChanging();
					this._SoTienThu = value;
					this.SendPropertyChanged("SoTienThu");
					this.OnSoTienThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="Char(10)")]
		public string MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					if (this._DAILY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaDaiLy = value;
					this.SendPropertyChanged("MaDaiLy");
					this.OnMaDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_PHIEUTHUTIEN", Storage="_DAILY", ThisKey="MaDaiLy", OtherKey="MaDaiLy", IsForeignKey=true)]
		public DAILY DAILY
		{
			get
			{
				return this._DAILY.Entity;
			}
			set
			{
				DAILY previousValue = this._DAILY.Entity;
				if (((previousValue != value) 
							|| (this._DAILY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DAILY.Entity = null;
						previousValue.PHIEUTHUTIENs.Remove(this);
					}
					this._DAILY.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHUTIENs.Add(this);
						this._MaDaiLy = value.MaDaiLy;
					}
					else
					{
						this._MaDaiLy = default(string);
					}
					this.SendPropertyChanged("DAILY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUXUAT_MATHANG")]
	public partial class PHIEUXUAT_MATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuXuat;
		
		private string _MaMatHang;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _ThanhTien;
		
		private System.Nullable<int> _MaDonViTinh;
		
		private EntityRef<DONVITINH> _DONVITINH;
		
		private EntityRef<MATHANG> _MATHANG;
		
		private EntityRef<PHIEUXUATHANG> _PHIEUXUATHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuXuatChanging(string value);
    partial void OnMaPhieuXuatChanged();
    partial void OnMaMatHangChanging(string value);
    partial void OnMaMatHangChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnThanhTienChanging(System.Nullable<int> value);
    partial void OnThanhTienChanged();
    partial void OnMaDonViTinhChanging(System.Nullable<int> value);
    partial void OnMaDonViTinhChanged();
    #endregion
		
		public PHIEUXUAT_MATHANG()
		{
			this._DONVITINH = default(EntityRef<DONVITINH>);
			this._MATHANG = default(EntityRef<MATHANG>);
			this._PHIEUXUATHANG = default(EntityRef<PHIEUXUATHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuXuat", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuXuat
		{
			get
			{
				return this._MaPhieuXuat;
			}
			set
			{
				if ((this._MaPhieuXuat != value))
				{
					if (this._PHIEUXUATHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuXuatChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuXuat = value;
					this.SendPropertyChanged("MaPhieuXuat");
					this.OnMaPhieuXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMatHang", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMatHang
		{
			get
			{
				return this._MaMatHang;
			}
			set
			{
				if ((this._MaMatHang != value))
				{
					if (this._MATHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMatHangChanging(value);
					this.SendPropertyChanging();
					this._MaMatHang = value;
					this.SendPropertyChanged("MaMatHang");
					this.OnMaMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonViTinh", DbType="Int")]
		public System.Nullable<int> MaDonViTinh
		{
			get
			{
				return this._MaDonViTinh;
			}
			set
			{
				if ((this._MaDonViTinh != value))
				{
					if (this._DONVITINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._MaDonViTinh = value;
					this.SendPropertyChanged("MaDonViTinh");
					this.OnMaDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONVITINH_PHIEUXUAT_MATHANG", Storage="_DONVITINH", ThisKey="MaDonViTinh", OtherKey="MaDonViTinh", IsForeignKey=true)]
		public DONVITINH DONVITINH
		{
			get
			{
				return this._DONVITINH.Entity;
			}
			set
			{
				DONVITINH previousValue = this._DONVITINH.Entity;
				if (((previousValue != value) 
							|| (this._DONVITINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONVITINH.Entity = null;
						previousValue.PHIEUXUAT_MATHANGs.Remove(this);
					}
					this._DONVITINH.Entity = value;
					if ((value != null))
					{
						value.PHIEUXUAT_MATHANGs.Add(this);
						this._MaDonViTinh = value.MaDonViTinh;
					}
					else
					{
						this._MaDonViTinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("DONVITINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATHANG_PHIEUXUAT_MATHANG", Storage="_MATHANG", ThisKey="MaMatHang", OtherKey="MaMatHang", IsForeignKey=true)]
		public MATHANG MATHANG
		{
			get
			{
				return this._MATHANG.Entity;
			}
			set
			{
				MATHANG previousValue = this._MATHANG.Entity;
				if (((previousValue != value) 
							|| (this._MATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MATHANG.Entity = null;
						previousValue.PHIEUXUAT_MATHANGs.Remove(this);
					}
					this._MATHANG.Entity = value;
					if ((value != null))
					{
						value.PHIEUXUAT_MATHANGs.Add(this);
						this._MaMatHang = value.MaMatHang;
					}
					else
					{
						this._MaMatHang = default(string);
					}
					this.SendPropertyChanged("MATHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUXUATHANG_PHIEUXUAT_MATHANG", Storage="_PHIEUXUATHANG", ThisKey="MaPhieuXuat", OtherKey="MaPhieuXuat", IsForeignKey=true)]
		public PHIEUXUATHANG PHIEUXUATHANG
		{
			get
			{
				return this._PHIEUXUATHANG.Entity;
			}
			set
			{
				PHIEUXUATHANG previousValue = this._PHIEUXUATHANG.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUXUATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUXUATHANG.Entity = null;
						previousValue.PHIEUXUAT_MATHANGs.Remove(this);
					}
					this._PHIEUXUATHANG.Entity = value;
					if ((value != null))
					{
						value.PHIEUXUAT_MATHANGs.Add(this);
						this._MaPhieuXuat = value.MaPhieuXuat;
					}
					else
					{
						this._MaPhieuXuat = default(string);
					}
					this.SendPropertyChanged("PHIEUXUATHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUXUATHANG")]
	public partial class PHIEUXUATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuXuat;
		
		private System.Nullable<System.DateTime> _NgayLapPhieu;
		
		private System.Nullable<int> _TongTien;
		
		private string _MaDaiLy;
		
		private EntitySet<PHIEUXUAT_MATHANG> _PHIEUXUAT_MATHANGs;
		
		private EntityRef<DAILY> _DAILY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuXuatChanging(string value);
    partial void OnMaPhieuXuatChanged();
    partial void OnNgayLapPhieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapPhieuChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    partial void OnMaDaiLyChanging(string value);
    partial void OnMaDaiLyChanged();
    #endregion
		
		public PHIEUXUATHANG()
		{
			this._PHIEUXUAT_MATHANGs = new EntitySet<PHIEUXUAT_MATHANG>(new Action<PHIEUXUAT_MATHANG>(this.attach_PHIEUXUAT_MATHANGs), new Action<PHIEUXUAT_MATHANG>(this.detach_PHIEUXUAT_MATHANGs));
			this._DAILY = default(EntityRef<DAILY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuXuat", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuXuat
		{
			get
			{
				return this._MaPhieuXuat;
			}
			set
			{
				if ((this._MaPhieuXuat != value))
				{
					this.OnMaPhieuXuatChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuXuat = value;
					this.SendPropertyChanged("MaPhieuXuat");
					this.OnMaPhieuXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapPhieu", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLapPhieu
		{
			get
			{
				return this._NgayLapPhieu;
			}
			set
			{
				if ((this._NgayLapPhieu != value))
				{
					this.OnNgayLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._NgayLapPhieu = value;
					this.SendPropertyChanged("NgayLapPhieu");
					this.OnNgayLapPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDaiLy", DbType="Char(10)")]
		public string MaDaiLy
		{
			get
			{
				return this._MaDaiLy;
			}
			set
			{
				if ((this._MaDaiLy != value))
				{
					if (this._DAILY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDaiLyChanging(value);
					this.SendPropertyChanging();
					this._MaDaiLy = value;
					this.SendPropertyChanged("MaDaiLy");
					this.OnMaDaiLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUXUATHANG_PHIEUXUAT_MATHANG", Storage="_PHIEUXUAT_MATHANGs", ThisKey="MaPhieuXuat", OtherKey="MaPhieuXuat")]
		public EntitySet<PHIEUXUAT_MATHANG> PHIEUXUAT_MATHANGs
		{
			get
			{
				return this._PHIEUXUAT_MATHANGs;
			}
			set
			{
				this._PHIEUXUAT_MATHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_PHIEUXUATHANG", Storage="_DAILY", ThisKey="MaDaiLy", OtherKey="MaDaiLy", IsForeignKey=true)]
		public DAILY DAILY
		{
			get
			{
				return this._DAILY.Entity;
			}
			set
			{
				DAILY previousValue = this._DAILY.Entity;
				if (((previousValue != value) 
							|| (this._DAILY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DAILY.Entity = null;
						previousValue.PHIEUXUATHANGs.Remove(this);
					}
					this._DAILY.Entity = value;
					if ((value != null))
					{
						value.PHIEUXUATHANGs.Add(this);
						this._MaDaiLy = value.MaDaiLy;
					}
					else
					{
						this._MaDaiLy = default(string);
					}
					this.SendPropertyChanged("DAILY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUXUAT_MATHANGs(PHIEUXUAT_MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUXUATHANG = this;
		}
		
		private void detach_PHIEUXUAT_MATHANGs(PHIEUXUAT_MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUXUATHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUAN")]
	public partial class QUAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaQuan;
		
		private string _TenQuan;
		
		private EntitySet<DAILY> _DAILies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuanChanging(string value);
    partial void OnMaQuanChanged();
    partial void OnTenQuanChanging(string value);
    partial void OnTenQuanChanged();
    #endregion
		
		public QUAN()
		{
			this._DAILies = new EntitySet<DAILY>(new Action<DAILY>(this.attach_DAILies), new Action<DAILY>(this.detach_DAILies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuan", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaQuan
		{
			get
			{
				return this._MaQuan;
			}
			set
			{
				if ((this._MaQuan != value))
				{
					this.OnMaQuanChanging(value);
					this.SendPropertyChanging();
					this._MaQuan = value;
					this.SendPropertyChanged("MaQuan");
					this.OnMaQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuan", DbType="NVarChar(50)")]
		public string TenQuan
		{
			get
			{
				return this._TenQuan;
			}
			set
			{
				if ((this._TenQuan != value))
				{
					this.OnTenQuanChanging(value);
					this.SendPropertyChanging();
					this._TenQuan = value;
					this.SendPropertyChanged("TenQuan");
					this.OnTenQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUAN_DAILY", Storage="_DAILies", ThisKey="MaQuan", OtherKey="MaQuan")]
		public EntitySet<DAILY> DAILies
		{
			get
			{
				return this._DAILies;
			}
			set
			{
				this._DAILies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DAILies(DAILY entity)
		{
			this.SendPropertyChanging();
			entity.QUAN = this;
		}
		
		private void detach_DAILies(DAILY entity)
		{
			this.SendPropertyChanging();
			entity.QUAN = null;
		}
	}
}
#pragma warning restore 1591
