<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyDaiLy" Class="QLDLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-KALP039;Initial Catalog=QuanLyDaiLy;Integrated Security=True" SettingsObjectName="Project.Properties.Settings" SettingsPropertyName="QuanLyDaiLyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BAOCAOCONGNO" Member="BAOCAOCONGNOs">
    <Type Name="BAOCAOCONGNO">
      <Column Name="MaBaoCaoCongNo" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BAOCAOCONGNO_CONGNO_DAILY" Member="CONGNO_DAILies" ThisKey="MaBaoCaoCongNo" OtherKey="MaBaoCaoCongNo" Type="CONGNO_DAILY" />
    </Type>
  </Table>
  <Table Name="dbo.THAMSO" Member="THAMSOs">
    <Type Name="THAMSO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoDaiLyToiDaQuan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoMatHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoDonViTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BAOCAODOANHSO" Member="BAOCAODOANHSOs">
    <Type Name="BAOCAODOANHSO">
      <Column Name="MaBaoCaoDoanhSo" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BAOCAODOANHSO_DOANHSO_DAILY" Member="DOANHSO_DAILies" ThisKey="MaBaoCaoDoanhSo" OtherKey="MaBaoCaoDoanhSo" Type="DOANHSO_DAILY" />
    </Type>
  </Table>
  <Table Name="dbo.CONGNO_DAILY" Member="CONGNO_DAILies">
    <Type Name="CONGNO_DAILY">
      <Column Name="MaBaoCaoCongNo" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDaiLy" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoDau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhatSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoCuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BAOCAOCONGNO_CONGNO_DAILY" Member="BAOCAOCONGNO" ThisKey="MaBaoCaoCongNo" OtherKey="MaBaoCaoCongNo" Type="BAOCAOCONGNO" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="DAILY_CONGNO_DAILY" Member="DAILY" ThisKey="MaDaiLy" OtherKey="MaDaiLy" Type="DAILY" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DAILY" Member="DAILies">
    <Type Name="DAILY">
      <Column Name="MaDaiLy" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDaiLy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(231)" CanBeNull="true" />
      <Column Name="NgayTiepNhan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="TienNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoaiDaiLy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaQuan" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="DAILY_CONGNO_DAILY" Member="CONGNO_DAILies" ThisKey="MaDaiLy" OtherKey="MaDaiLy" Type="CONGNO_DAILY" />
      <Association Name="DAILY_DOANHSO_DAILY" Member="DOANHSO_DAILies" ThisKey="MaDaiLy" OtherKey="MaDaiLy" Type="DOANHSO_DAILY" />
      <Association Name="DAILY_PHIEUTHUTIEN" Member="PHIEUTHUTIENs" ThisKey="MaDaiLy" OtherKey="MaDaiLy" Type="PHIEUTHUTIEN" />
      <Association Name="DAILY_PHIEUXUATHANG" Member="PHIEUXUATHANGs" ThisKey="MaDaiLy" OtherKey="MaDaiLy" Type="PHIEUXUATHANG" />
      <Association Name="LOAIDAILY_DAILY" Member="LOAIDAILY" ThisKey="MaLoaiDaiLy" OtherKey="MaLoaiDaiLy" Type="LOAIDAILY" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="QUAN_DAILY" Member="QUAN" ThisKey="MaQuan" OtherKey="MaQuan" Type="QUAN" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.DOANHSO_DAILY" Member="DOANHSO_DAILies">
    <Type Name="DOANHSO_DAILY">
      <Column Name="MaBaoCaoDoanhSo" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDaiLy" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoPhieuXuat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTriGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TyLe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DAILY_DOANHSO_DAILY" Member="DAILY" ThisKey="MaDaiLy" OtherKey="MaDaiLy" Type="DAILY" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="BAOCAODOANHSO_DOANHSO_DAILY" Member="BAOCAODOANHSO" ThisKey="MaBaoCaoDoanhSo" OtherKey="MaBaoCaoDoanhSo" Type="BAOCAODOANHSO" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONVITINH" Member="DONVITINHs">
    <Type Name="DONVITINH">
      <Column Name="MaDonViTinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDonViTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DONVITINH_PHIEUXUAT_MATHANG" Member="PHIEUXUAT_MATHANGs" ThisKey="MaDonViTinh" OtherKey="MaDonViTinh" Type="PHIEUXUAT_MATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIDAILY" Member="LOAIDAILies">
    <Type Name="LOAIDAILY">
      <Column Name="MaLoaiDaiLy" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiDaiLy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TienNoToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LOAIDAILY_DAILY" Member="DAILies" ThisKey="MaLoaiDaiLy" OtherKey="MaLoaiDaiLy" Type="DAILY" />
    </Type>
  </Table>
  <Table Name="dbo.MATHANG" Member="MATHANGs">
    <Type Name="MATHANG">
      <Column Name="MaMatHang" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMatHang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MATHANG_PHIEUXUAT_MATHANG" Member="PHIEUXUAT_MATHANGs" ThisKey="MaMatHang" OtherKey="MaMatHang" Type="PHIEUXUAT_MATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUTHUTIEN" Member="PHIEUTHUTIENs">
    <Type Name="PHIEUTHUTIEN">
      <Column Name="MaPhieuThu" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayThuTien" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoTienThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDaiLy" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="DAILY_PHIEUTHUTIEN" Member="DAILY" ThisKey="MaDaiLy" OtherKey="MaDaiLy" Type="DAILY" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUXUAT_MATHANG" Member="PHIEUXUAT_MATHANGs">
    <Type Name="PHIEUXUAT_MATHANG">
      <Column Name="MaPhieuXuat" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaMatHang" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDonViTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DONVITINH_PHIEUXUAT_MATHANG" Member="DONVITINH" ThisKey="MaDonViTinh" OtherKey="MaDonViTinh" Type="DONVITINH" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="MATHANG_PHIEUXUAT_MATHANG" Member="MATHANG" ThisKey="MaMatHang" OtherKey="MaMatHang" Type="MATHANG" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="PHIEUXUATHANG_PHIEUXUAT_MATHANG" Member="PHIEUXUATHANG" ThisKey="MaPhieuXuat" OtherKey="MaPhieuXuat" Type="PHIEUXUATHANG" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUXUATHANG" Member="PHIEUXUATHANGs">
    <Type Name="PHIEUXUATHANG">
      <Column Name="MaPhieuXuat" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLapPhieu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDaiLy" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="PHIEUXUATHANG_PHIEUXUAT_MATHANG" Member="PHIEUXUAT_MATHANGs" ThisKey="MaPhieuXuat" OtherKey="MaPhieuXuat" Type="PHIEUXUAT_MATHANG" />
      <Association Name="DAILY_PHIEUXUATHANG" Member="DAILY" ThisKey="MaDaiLy" OtherKey="MaDaiLy" Type="DAILY" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.QUAN" Member="QUANs">
    <Type Name="QUAN">
      <Column Name="MaQuan" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QUAN_DAILY" Member="DAILies" ThisKey="MaQuan" OtherKey="MaQuan" Type="DAILY" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TenTaiKhoan" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="Char(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>